// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#ifndef _BLUEKNOB_UI_H
#define _BLUEKNOB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_screenMediaControls.h"
#include "screens/ui_screenSettings.h"
#include "screens/ui_screenDpad.h"
#include "screens/ui_screenTrackpad.h"
#include "screens/ui_screenBlank.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg001_png);    // assets/bg001.png
LV_IMG_DECLARE(ui_img_bg002_png);    // assets/bg002.png
LV_IMG_DECLARE(ui_img_bg003_png);    // assets/bg003.png
LV_IMG_DECLARE(ui_img_bg004_png);    // assets/bg004.png
LV_IMG_DECLARE(ui_img_bg005_png);    // assets/bg005.png
LV_IMG_DECLARE(ui_img_bg006_png);    // assets/bg006.png
LV_IMG_DECLARE(ui_img_bg007_png);    // assets/bg007.png
LV_IMG_DECLARE(ui_img_bg008_png);    // assets/bg008.png
LV_IMG_DECLARE(ui_img_bg009_png);    // assets/bg009.png
LV_IMG_DECLARE(ui_img_bg010_png);    // assets/bg010.png
LV_IMG_DECLARE(ui_img_bg011_png);    // assets/bg011.png
LV_IMG_DECLARE(ui_img_bg012_png);    // assets/bg012.png
LV_IMG_DECLARE(ui_img_bg013_png);    // assets/bg013.png
LV_IMG_DECLARE(ui_img_bg014_png);    // assets/bg014.png
LV_IMG_DECLARE(ui_img_bg015_png);    // assets/bg015.png
LV_IMG_DECLARE(ui_img_bg016_png);    // assets/bg016.png
LV_IMG_DECLARE(ui_img_bg017_png);    // assets/bg017.png
LV_IMG_DECLARE(ui_img_bg018_png);    // assets/bg018.png
LV_IMG_DECLARE(ui_img_bg019_png);    // assets/bg019.png
LV_IMG_DECLARE(ui_img_bg020_png);    // assets/bg020.png
LV_IMG_DECLARE(ui_img_bg021_png);    // assets/bg021.png
LV_IMG_DECLARE(ui_img_bg022_png);    // assets/bg022.png
LV_IMG_DECLARE(ui_img_bg023_png);    // assets/bg023.png
LV_IMG_DECLARE(ui_img_bg024_png);    // assets/bg024.png
LV_IMG_DECLARE(ui_img_trackpad_png);    // assets/trackpad.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
