// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void screenMediaControls_onGestureLeft(lv_event_t * e);
void screenMediaControls_onGestureRight(lv_event_t * e);
void anyButton_onPressed(lv_event_t * e);
void buttonPlay_onLongPressed(lv_event_t * e);
void buttonPlay_onShortClicked(lv_event_t * e);
void buttonPrev_onLongPressed(lv_event_t * e);
void buttonPrev_onShortClicked(lv_event_t * e);
void buttonNext_onLongPressed(lv_event_t * e);
void buttonNext_onShortClicked(lv_event_t * e);
void screenSettings_onGestureLeft(lv_event_t * e);
void screenSettings_onGestureRight(lv_event_t * e);
void brightnessArc_onValueChanged(lv_event_t * e);
void rollerDisplay_onValueChanged(lv_event_t * e);
void switchTheme_onShortClicked(lv_event_t * e);
void rollerDevice_onValueChanged(lv_event_t * e);
void screenDpad_onGestureLeft(lv_event_t * e);
void screenDpad_onGestureRight(lv_event_t * e);
void buttonDpadUp_onShortClicked(lv_event_t * e);
void buttonDpadDown_onShortClicked(lv_event_t * e);
void buttonDpadLeft_onShortClicked(lv_event_t * e);
void buttonDpadRight_onShortClicked(lv_event_t * e);
void buttonDpadEnter_onShortClicked(lv_event_t * e);
void buttonDpadEnter_onLongPressed(lv_event_t * e);
void buttonDpadBack_onShortClicked(lv_event_t * e);
void buttonDpadBack_onLongPressed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
