// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#include "../ui.h"

lv_obj_t * ui_screenSettings = NULL;
lv_obj_t * ui_brightnessArc = NULL;
lv_obj_t * ui_barBattery = NULL;
lv_obj_t * ui_buttonBatteryDummy = NULL;
lv_obj_t * ui_rollerDisplay = NULL;
lv_obj_t * ui_switchTheme = NULL;
lv_obj_t * ui_rollerDevice = NULL;
lv_obj_t * ui_labelBrightness = NULL;
lv_obj_t * ui_labelVoltage = NULL;
lv_obj_t * ui_labelBattery = NULL;
lv_obj_t * ui_labelTheme = NULL;
lv_obj_t * ui_labelSleepDisplay = NULL;
lv_obj_t * ui_labelSleepDevice = NULL;
// event funtions
void ui_event_screenSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        screenSettings_onGestureLeft(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        screenSettings_onGestureRight(e);
    }
}

void ui_event_brightnessArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        brightnessArc_onValueChanged(e);
    }
}

void ui_event_rollerDisplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rollerDisplay_onValueChanged(e);
    }
}

void ui_event_switchTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        switchTheme_onShortClicked(e);
    }
}

void ui_event_rollerDevice(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rollerDevice_onValueChanged(e);
    }
}

// build funtions

void ui_screenSettings_screen_init(void)
{
    ui_screenSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenSettings, lv_color_hex(0x2F3139), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brightnessArc = lv_arc_create(ui_screenSettings);
    lv_obj_set_width(ui_brightnessArc, 280);
    lv_obj_set_height(ui_brightnessArc, 280);
    lv_obj_set_x(ui_brightnessArc, 0);
    lv_obj_set_y(ui_brightnessArc, 32);
    lv_obj_set_align(ui_brightnessArc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_brightnessArc, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_brightnessArc, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_range(ui_brightnessArc, 5, 255);
    lv_arc_set_value(ui_brightnessArc, 160);
    lv_arc_set_bg_angles(ui_brightnessArc, 0, 120);
    lv_arc_set_rotation(ui_brightnessArc, 30);
    lv_obj_set_style_bg_color(ui_brightnessArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_brightnessArc, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_brightnessArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brightnessArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessArc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_brightnessArc, lv_color_hex(0x6A82DD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_brightnessArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brightnessArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brightnessArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brightnessArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brightnessArc, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_barBattery = lv_bar_create(ui_screenSettings);
    lv_bar_set_value(ui_barBattery, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barBattery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barBattery, 300);
    lv_obj_set_height(ui_barBattery, 23);
    lv_obj_set_x(ui_barBattery, 303);
    lv_obj_set_y(ui_barBattery, 93);
    lv_obj_set_align(ui_barBattery, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barBattery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barBattery, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_barBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_barBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_barBattery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_barBattery, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_barBattery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_barBattery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_barBattery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_barBattery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_barBattery, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barBattery, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barBattery, lv_color_hex(0x18A917), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barBattery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_buttonBatteryDummy = lv_btn_create(ui_screenSettings);
    lv_obj_set_width(ui_buttonBatteryDummy, 6);
    lv_obj_set_height(ui_buttonBatteryDummy, 11);
    lv_obj_set_x(ui_buttonBatteryDummy, -150);
    lv_obj_set_y(ui_buttonBatteryDummy, 71);
    lv_obj_set_align(ui_buttonBatteryDummy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonBatteryDummy, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonBatteryDummy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonBatteryDummy, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonBatteryDummy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonBatteryDummy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerDisplay = lv_roller_create(ui_screenSettings);
    lv_roller_set_options(ui_rollerDisplay, "10s\n20s\n30s\n1m\n3m\n5m", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_rollerDisplay, 125);
    lv_obj_set_width(ui_rollerDisplay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_rollerDisplay, 174);
    lv_obj_set_y(ui_rollerDisplay, 88);
    lv_obj_set_align(ui_rollerDisplay, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_rollerDisplay, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerDisplay, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerDisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_rollerDisplay, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rollerDisplay, lv_color_hex(0x6A82DD), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerDisplay, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_switchTheme = lv_switch_create(ui_screenSettings);
    lv_obj_set_width(ui_switchTheme, 60);
    lv_obj_set_height(ui_switchTheme, 30);
    lv_obj_set_x(ui_switchTheme, 60);
    lv_obj_set_y(ui_switchTheme, 15);
    lv_obj_set_align(ui_switchTheme, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_switchTheme, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switchTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_switchTheme, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switchTheme, lv_color_hex(0x6A82DD), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switchTheme, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_switchTheme, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switchTheme, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_switchTheme, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_switchTheme, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_switchTheme, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_rollerDevice = lv_roller_create(ui_screenSettings);
    lv_roller_set_options(ui_rollerDevice, "1m\n3m\n5m\n10m\n15m\n30m", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_rollerDevice, 125);
    lv_obj_set_width(ui_rollerDevice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_rollerDevice, -26);
    lv_obj_set_y(ui_rollerDevice, 88);
    lv_obj_set_align(ui_rollerDevice, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_rollerDevice, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerDevice, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerDevice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rollerDevice, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_rollerDevice, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rollerDevice, lv_color_hex(0x6A82DD), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerDevice, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_labelBrightness = lv_label_create(ui_screenSettings);
    lv_obj_set_width(ui_labelBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBrightness, 114);
    lv_obj_set_y(ui_labelBrightness, 149);
    lv_obj_set_align(ui_labelBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBrightness, "Brightness");
    lv_obj_set_style_text_font(ui_labelBrightness, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_labelBrightness, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelVoltage = lv_label_create(ui_screenSettings);
    lv_obj_set_width(ui_labelVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelVoltage, 82);
    lv_obj_set_y(ui_labelVoltage, 162);
    lv_obj_set_align(ui_labelVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelVoltage, "");
    lv_obj_add_flag(ui_labelVoltage, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_labelVoltage, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_labelVoltage, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBattery = lv_label_create(ui_screenSettings);
    lv_obj_set_width(ui_labelBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBattery, 76);
    lv_obj_set_y(ui_labelBattery, 83);
    lv_obj_set_align(ui_labelBattery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBattery, "Battery");
    lv_obj_add_flag(ui_labelBattery, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_labelBattery, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_labelBattery, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTheme = lv_label_create(ui_screenSettings);
    lv_obj_set_width(ui_labelTheme, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTheme, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTheme, 70);
    lv_obj_set_y(ui_labelTheme, 33);
    lv_obj_set_align(ui_labelTheme, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTheme, "Theme");
    lv_obj_set_style_text_font(ui_labelTheme, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_labelTheme, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSleepDisplay = lv_label_create(ui_screenSettings);
    lv_obj_set_width(ui_labelSleepDisplay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSleepDisplay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelSleepDisplay, 184);
    lv_obj_set_y(ui_labelSleepDisplay, 61);
    lv_obj_set_align(ui_labelSleepDisplay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSleepDisplay, "Display");
    lv_obj_set_style_text_font(ui_labelSleepDisplay, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_labelSleepDisplay, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSleepDevice = lv_label_create(ui_screenSettings);
    lv_obj_set_width(ui_labelSleepDevice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSleepDevice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelSleepDevice, -35);
    lv_obj_set_y(ui_labelSleepDevice, 61);
    lv_obj_set_align(ui_labelSleepDevice, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSleepDevice, "Device");
    lv_obj_set_style_text_font(ui_labelSleepDevice, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_labelSleepDevice, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_brightnessArc, ui_event_brightnessArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rollerDisplay, ui_event_rollerDisplay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchTheme, ui_event_switchTheme, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rollerDevice, ui_event_rollerDevice, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenSettings, ui_event_screenSettings, LV_EVENT_ALL, NULL);

}

void ui_screenSettings_screen_destroy(void)
{
    if(ui_screenSettings) lv_obj_del(ui_screenSettings);

    // NULL screen variables
    ui_screenSettings = NULL;
    ui_brightnessArc = NULL;
    ui_barBattery = NULL;
    ui_buttonBatteryDummy = NULL;
    ui_rollerDisplay = NULL;
    ui_switchTheme = NULL;
    ui_rollerDevice = NULL;
    ui_labelBrightness = NULL;
    ui_labelVoltage = NULL;
    ui_labelBattery = NULL;
    ui_labelTheme = NULL;
    ui_labelSleepDisplay = NULL;
    ui_labelSleepDevice = NULL;

}
