// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#include "../ui.h"

lv_obj_t * ui_screenBlank = NULL;
// event funtions

// build funtions

void ui_screenBlank_screen_init(void)
{
    ui_screenBlank = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenBlank, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenBlank, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenBlank, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_screenBlank_screen_destroy(void)
{
    if(ui_screenBlank) lv_obj_del(ui_screenBlank);

    // NULL screen variables
    ui_screenBlank = NULL;

}
