// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#ifndef UI_SCREENBLANK_H
#define UI_SCREENBLANK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenBlank
extern void ui_screenBlank_screen_init(void);
extern void ui_screenBlank_screen_destroy(void);
extern lv_obj_t * ui_screenBlank;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

