// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#ifndef UI_SCREENTRACKPAD_H
#define UI_SCREENTRACKPAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenTrackpad
extern void ui_screenTrackpad_screen_init(void);
extern void ui_screenTrackpad_screen_destroy(void);
extern lv_obj_t * ui_screenTrackpad;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

