// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#include "../ui.h"

lv_obj_t * ui_screenMediaControls = NULL;
lv_obj_t * ui_buttonPlay = NULL;
lv_obj_t * ui_buttonPrev = NULL;
lv_obj_t * ui_buttonNext = NULL;
lv_obj_t * ui_labelPlay = NULL;
lv_obj_t * ui_labelPrev = NULL;
lv_obj_t * ui_labelNext = NULL;
lv_obj_t * ui_labelBluetooth = NULL;
// event funtions
void ui_event_screenMediaControls(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        screenMediaControls_onGestureLeft(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        screenMediaControls_onGestureRight(e);
    }
}

void ui_event_buttonPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        anyButton_onPressed(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        buttonPlay_onLongPressed(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        buttonPlay_onShortClicked(e);
    }
}

void ui_event_buttonPrev(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        anyButton_onPressed(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        buttonPrev_onLongPressed(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        buttonPrev_onShortClicked(e);
    }
}

void ui_event_buttonNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        anyButton_onPressed(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        buttonNext_onLongPressed(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        buttonNext_onShortClicked(e);
    }
}

// build funtions

void ui_screenMediaControls_screen_init(void)
{
    ui_screenMediaControls = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenMediaControls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_screenMediaControls, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_screenMediaControls, lv_color_hex(0xDB057B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenMediaControls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_screenMediaControls, lv_color_hex(0xDFA225), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_screenMediaControls, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_screenMediaControls, 190, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_screenMediaControls, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_screenMediaControls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_screenMediaControls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_screenMediaControls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_screenMediaControls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonPlay = lv_btn_create(ui_screenMediaControls);
    lv_obj_set_width(ui_buttonPlay, 120);
    lv_obj_set_height(ui_buttonPlay, 120);
    lv_obj_set_align(ui_buttonPlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonPlay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonPlay, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonPlay, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonPlay, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonPlay, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_buttonPlay, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonPrev = lv_btn_create(ui_screenMediaControls);
    lv_obj_set_width(ui_buttonPrev, 80);
    lv_obj_set_height(ui_buttonPrev, 80);
    lv_obj_set_x(ui_buttonPrev, 134);
    lv_obj_set_y(ui_buttonPrev, 0);
    lv_obj_set_align(ui_buttonPrev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonPrev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonPrev, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonPrev, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonPrev, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonPrev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonPrev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonPrev, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_buttonPrev, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonNext = lv_btn_create(ui_screenMediaControls);
    lv_obj_set_width(ui_buttonNext, 80);
    lv_obj_set_height(ui_buttonNext, 80);
    lv_obj_set_x(ui_buttonNext, -134);
    lv_obj_set_y(ui_buttonNext, 0);
    lv_obj_set_align(ui_buttonNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_buttonNext, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonNext, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonNext, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonNext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonNext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonNext, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_buttonNext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPlay = lv_label_create(ui_screenMediaControls);
    lv_obj_set_width(ui_labelPlay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlay, 43);
    lv_obj_set_y(ui_labelPlay, 65);
    lv_obj_set_align(ui_labelPlay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPlay, "");
    lv_obj_clear_flag(ui_labelPlay, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_labelPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPlay, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_labelPlay, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_labelPlay, 400, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPrev = lv_label_create(ui_screenMediaControls);
    lv_obj_set_width(ui_labelPrev, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPrev, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPrev, 134);
    lv_obj_set_y(ui_labelPrev, 0);
    lv_obj_set_align(ui_labelPrev, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPrev, "");
    lv_obj_clear_flag(ui_labelPrev, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_labelPrev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelPrev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPrev, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelNext = lv_label_create(ui_screenMediaControls);
    lv_obj_set_width(ui_labelNext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelNext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelNext, -134);
    lv_obj_set_y(ui_labelNext, 0);
    lv_obj_set_align(ui_labelNext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelNext, "");
    lv_obj_clear_flag(ui_labelNext, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_labelNext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelNext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelNext, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBluetooth = lv_label_create(ui_screenMediaControls);
    lv_obj_set_width(ui_labelBluetooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBluetooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBluetooth, 35);
    lv_obj_set_y(ui_labelBluetooth, 188);
    lv_obj_set_align(ui_labelBluetooth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBluetooth, "");
    lv_obj_set_style_text_color(ui_labelBluetooth, lv_color_hex(0x4E4E4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBluetooth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_labelBluetooth, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBluetooth, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_labelBluetooth, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_labelBluetooth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_labelBluetooth, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_labelBluetooth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_labelBluetooth, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labelBluetooth, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labelBluetooth, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labelBluetooth, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labelBluetooth, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_labelBluetooth, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonPlay, ui_event_buttonPlay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonPrev, ui_event_buttonPrev, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonNext, ui_event_buttonNext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenMediaControls, ui_event_screenMediaControls, LV_EVENT_ALL, NULL);

}

void ui_screenMediaControls_screen_destroy(void)
{
    if(ui_screenMediaControls) lv_obj_del(ui_screenMediaControls);

    // NULL screen variables
    ui_screenMediaControls = NULL;
    ui_buttonPlay = NULL;
    ui_buttonPrev = NULL;
    ui_buttonNext = NULL;
    ui_labelPlay = NULL;
    ui_labelPrev = NULL;
    ui_labelNext = NULL;
    ui_labelBluetooth = NULL;

}
