// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenSettings
extern void ui_screenSettings_screen_init(void);
extern void ui_screenSettings_screen_destroy(void);
extern void ui_event_screenSettings(lv_event_t * e);
extern lv_obj_t * ui_screenSettings;
extern void ui_event_brightnessArc(lv_event_t * e);
extern lv_obj_t * ui_brightnessArc;
extern lv_obj_t * ui_barBattery;
extern lv_obj_t * ui_buttonBatteryDummy;
extern void ui_event_rollerDisplay(lv_event_t * e);
extern lv_obj_t * ui_rollerDisplay;
extern void ui_event_switchTheme(lv_event_t * e);
extern lv_obj_t * ui_switchTheme;
extern void ui_event_rollerDevice(lv_event_t * e);
extern lv_obj_t * ui_rollerDevice;
extern lv_obj_t * ui_labelBrightness;
extern lv_obj_t * ui_labelVoltage;
extern lv_obj_t * ui_labelBattery;
extern lv_obj_t * ui_labelTheme;
extern lv_obj_t * ui_labelSleepDisplay;
extern lv_obj_t * ui_labelSleepDevice;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

