// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#include "../ui.h"

lv_obj_t * ui_screenTrackpad = NULL;
// event funtions

// build funtions

void ui_screenTrackpad_screen_init(void)
{
    ui_screenTrackpad = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenTrackpad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenTrackpad, lv_color_hex(0x112110), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenTrackpad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_screenTrackpad_screen_destroy(void)
{
    if(ui_screenTrackpad) lv_obj_del(ui_screenTrackpad);

    // NULL screen variables
    ui_screenTrackpad = NULL;

}
