// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#ifndef UI_SCREENMEDIACONTROLS_H
#define UI_SCREENMEDIACONTROLS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenMediaControls
extern void ui_screenMediaControls_screen_init(void);
extern void ui_screenMediaControls_screen_destroy(void);
extern void ui_event_screenMediaControls(lv_event_t * e);
extern lv_obj_t * ui_screenMediaControls;
extern void ui_event_buttonPlay(lv_event_t * e);
extern lv_obj_t * ui_buttonPlay;
extern void ui_event_buttonPrev(lv_event_t * e);
extern lv_obj_t * ui_buttonPrev;
extern void ui_event_buttonNext(lv_event_t * e);
extern lv_obj_t * ui_buttonNext;
extern lv_obj_t * ui_labelPlay;
extern lv_obj_t * ui_labelPrev;
extern lv_obj_t * ui_labelNext;
extern lv_obj_t * ui_labelBluetooth;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

