// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#include "../ui.h"

lv_obj_t * ui_screenDpad = NULL;
lv_obj_t * ui_buttonDpadUp = NULL;
lv_obj_t * ui_buttonDpadDown = NULL;
lv_obj_t * ui_buttonDpadLeft = NULL;
lv_obj_t * ui_buttonDpadRight = NULL;
lv_obj_t * ui_buttonDpadEnter = NULL;
lv_obj_t * ui_buttonDpadBack = NULL;
lv_obj_t * ui_labelUp = NULL;
lv_obj_t * ui_labelDown = NULL;
lv_obj_t * ui_labelLeft = NULL;
lv_obj_t * ui_labelRight = NULL;
lv_obj_t * ui_labelEnter = NULL;
lv_obj_t * ui_labelBack = NULL;
// event funtions
void ui_event_screenDpad(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        screenDpad_onGestureLeft(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        screenDpad_onGestureRight(e);
    }
}

void ui_event_buttonDpadUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        buttonDpadUp_onShortClicked(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        anyButton_onPressed(e);
    }
}

void ui_event_buttonDpadDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        buttonDpadDown_onShortClicked(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        anyButton_onPressed(e);
    }
}

void ui_event_buttonDpadLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        buttonDpadLeft_onShortClicked(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        anyButton_onPressed(e);
    }
}

void ui_event_buttonDpadRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        buttonDpadRight_onShortClicked(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        anyButton_onPressed(e);
    }
}

void ui_event_buttonDpadEnter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        buttonDpadEnter_onShortClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        buttonDpadEnter_onLongPressed(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        anyButton_onPressed(e);
    }
}

void ui_event_buttonDpadBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        buttonDpadBack_onShortClicked(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        buttonDpadBack_onLongPressed(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        anyButton_onPressed(e);
    }
}

// build funtions

void ui_screenDpad_screen_init(void)
{
    ui_screenDpad = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenDpad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenDpad, lv_color_hex(0x353129), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenDpad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDpadUp = lv_btn_create(ui_screenDpad);
    lv_obj_set_width(ui_buttonDpadUp, 80);
    lv_obj_set_height(ui_buttonDpadUp, 80);
    lv_obj_set_x(ui_buttonDpadUp, 0);
    lv_obj_set_y(ui_buttonDpadUp, 126);
    lv_obj_set_align(ui_buttonDpadUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDpadUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonDpadUp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonDpadUp, lv_color_hex(0x9E9E90), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDpadUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonDpadUp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonDpadUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonDpadUp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDpadDown = lv_btn_create(ui_screenDpad);
    lv_obj_set_width(ui_buttonDpadDown, 80);
    lv_obj_set_height(ui_buttonDpadDown, 80);
    lv_obj_set_x(ui_buttonDpadDown, 0);
    lv_obj_set_y(ui_buttonDpadDown, 22);
    lv_obj_set_align(ui_buttonDpadDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDpadDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonDpadDown, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonDpadDown, lv_color_hex(0x9E9E90), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDpadDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonDpadDown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonDpadDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonDpadDown, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDpadLeft = lv_btn_create(ui_screenDpad);
    lv_obj_set_width(ui_buttonDpadLeft, 80);
    lv_obj_set_height(ui_buttonDpadLeft, 80);
    lv_obj_set_x(ui_buttonDpadLeft, 97);
    lv_obj_set_y(ui_buttonDpadLeft, 76);
    lv_obj_set_align(ui_buttonDpadLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDpadLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonDpadLeft, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonDpadLeft, lv_color_hex(0x9E9E90), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDpadLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonDpadLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonDpadLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonDpadLeft, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDpadRight = lv_btn_create(ui_screenDpad);
    lv_obj_set_width(ui_buttonDpadRight, 80);
    lv_obj_set_height(ui_buttonDpadRight, 80);
    lv_obj_set_x(ui_buttonDpadRight, -97);
    lv_obj_set_y(ui_buttonDpadRight, 76);
    lv_obj_set_align(ui_buttonDpadRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDpadRight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonDpadRight, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonDpadRight, lv_color_hex(0x9E9E90), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDpadRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonDpadRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonDpadRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonDpadRight, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDpadEnter = lv_btn_create(ui_screenDpad);
    lv_obj_set_width(ui_buttonDpadEnter, 80);
    lv_obj_set_height(ui_buttonDpadEnter, 80);
    lv_obj_set_x(ui_buttonDpadEnter, -97);
    lv_obj_set_y(ui_buttonDpadEnter, -38);
    lv_obj_set_align(ui_buttonDpadEnter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDpadEnter, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonDpadEnter, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonDpadEnter, lv_color_hex(0x9E9E90), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDpadEnter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonDpadEnter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonDpadEnter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonDpadEnter, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonDpadBack = lv_btn_create(ui_screenDpad);
    lv_obj_set_width(ui_buttonDpadBack, 80);
    lv_obj_set_height(ui_buttonDpadBack, 80);
    lv_obj_set_x(ui_buttonDpadBack, 97);
    lv_obj_set_y(ui_buttonDpadBack, -38);
    lv_obj_set_align(ui_buttonDpadBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonDpadBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonDpadBack, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonDpadBack, lv_color_hex(0x9E9E90), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonDpadBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonDpadBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonDpadBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonDpadBack, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelUp = lv_label_create(ui_screenDpad);
    lv_obj_set_width(ui_labelUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelUp, -5);
    lv_obj_set_y(ui_labelUp, 126);
    lv_obj_set_align(ui_labelUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelUp, "");
    lv_obj_set_style_text_color(ui_labelUp, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelUp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_labelUp, 320, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelDown = lv_label_create(ui_screenDpad);
    lv_obj_set_width(ui_labelDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDown, -5);
    lv_obj_set_y(ui_labelDown, 13);
    lv_obj_set_align(ui_labelDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDown, "");
    lv_obj_set_style_text_color(ui_labelDown, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelDown, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_labelDown, 320, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelLeft = lv_label_create(ui_screenDpad);
    lv_obj_set_width(ui_labelLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelLeft, 97);
    lv_obj_set_y(ui_labelLeft, 71);
    lv_obj_set_align(ui_labelLeft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelLeft, "");
    lv_obj_set_style_text_color(ui_labelLeft, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelLeft, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_labelLeft, 320, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelRight = lv_label_create(ui_screenDpad);
    lv_obj_set_width(ui_labelRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelRight, -109);
    lv_obj_set_y(ui_labelRight, 71);
    lv_obj_set_align(ui_labelRight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelRight, "");
    lv_obj_set_style_text_color(ui_labelRight, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelRight, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_labelRight, 320, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelEnter = lv_label_create(ui_screenDpad);
    lv_obj_set_width(ui_labelEnter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelEnter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelEnter, -44);
    lv_obj_set_y(ui_labelEnter, 19);
    lv_obj_set_align(ui_labelEnter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelEnter, "");
    lv_obj_set_style_text_color(ui_labelEnter, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelEnter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelEnter, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_labelEnter, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_labelEnter, 320, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBack = lv_label_create(ui_screenDpad);
    lv_obj_set_width(ui_labelBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBack, 137);
    lv_obj_set_y(ui_labelBack, 24);
    lv_obj_set_align(ui_labelBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBack, "");
    lv_obj_set_style_text_color(ui_labelBack, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBack, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_labelBack, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_labelBack, 380, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonDpadUp, ui_event_buttonDpadUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDpadDown, ui_event_buttonDpadDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDpadLeft, ui_event_buttonDpadLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDpadRight, ui_event_buttonDpadRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDpadEnter, ui_event_buttonDpadEnter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonDpadBack, ui_event_buttonDpadBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenDpad, ui_event_screenDpad, LV_EVENT_ALL, NULL);

}

void ui_screenDpad_screen_destroy(void)
{
    if(ui_screenDpad) lv_obj_del(ui_screenDpad);

    // NULL screen variables
    ui_screenDpad = NULL;
    ui_buttonDpadUp = NULL;
    ui_buttonDpadDown = NULL;
    ui_buttonDpadLeft = NULL;
    ui_buttonDpadRight = NULL;
    ui_buttonDpadEnter = NULL;
    ui_buttonDpadBack = NULL;
    ui_labelUp = NULL;
    ui_labelDown = NULL;
    ui_labelLeft = NULL;
    ui_labelRight = NULL;
    ui_labelEnter = NULL;
    ui_labelBack = NULL;

}
