// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: BlueKnob

#ifndef UI_SCREENDPAD_H
#define UI_SCREENDPAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenDpad
extern void ui_screenDpad_screen_init(void);
extern void ui_screenDpad_screen_destroy(void);
extern void ui_event_screenDpad(lv_event_t * e);
extern lv_obj_t * ui_screenDpad;
extern void ui_event_buttonDpadUp(lv_event_t * e);
extern lv_obj_t * ui_buttonDpadUp;
extern void ui_event_buttonDpadDown(lv_event_t * e);
extern lv_obj_t * ui_buttonDpadDown;
extern void ui_event_buttonDpadLeft(lv_event_t * e);
extern lv_obj_t * ui_buttonDpadLeft;
extern void ui_event_buttonDpadRight(lv_event_t * e);
extern lv_obj_t * ui_buttonDpadRight;
extern void ui_event_buttonDpadEnter(lv_event_t * e);
extern lv_obj_t * ui_buttonDpadEnter;
extern void ui_event_buttonDpadBack(lv_event_t * e);
extern lv_obj_t * ui_buttonDpadBack;
extern lv_obj_t * ui_labelUp;
extern lv_obj_t * ui_labelDown;
extern lv_obj_t * ui_labelLeft;
extern lv_obj_t * ui_labelRight;
extern lv_obj_t * ui_labelEnter;
extern lv_obj_t * ui_labelBack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

